export const ollCases = [
  {
    name: "Aa",
    moves: "x L2 D2 L' U' L D2 L' U L'",
    description: "Adjacent Corner Swap",
    category: "OLL",
  },
  {
    name: "Ab",
    moves: "x' L2 D2 L U L' D2 L U' L",
    description: "Adjacent Corner Swap",
    category: "OLL",
  },
  {
    name: "E",
    moves: "x' L' U L D' L' U' L D L' U' L D' L' U L D",
    description: "Diagonal Corner Swap",
    category: "OLL",
  },
  {
    name: "F",
    moves: "R' U' F' R U R' U' R' F R2 U' R' U' R U R' U R",
    description: "Adjacent Corner Swap",
    category: "OLL",
  },
  {
    name: "Ga",
    moves: "R2 U R' U R' U' R U' R2 U' D R' U R D'",
    description: "Adjacent Corner Swap",
    category: "OLL",
  },
  {
    name: "Gb",
    moves: "R' U' R U D' R2 U R' U R U' R U' R2 D",
    description: "Adjacent Corner Swap",
    category: "OLL",
  },
  {
    name: "Gc",
    moves: "R2 U' R U' R U R' U R2 U D' R U' R' D",
    description: "Adjacent Corner Swap",
    category: "OLL",
  },
  {
    name: "Gd",
    moves: "R U R' U' D R2 U' R U' R' U R' U R2 D'",
    description: "Adjacent Corner Swap",
    category: "OLL",
  },
  {
    name: "H",
    moves: "M2 U M2 U2 M2 U M2",
    description: "Edges Only",
    category: "OLL",
  },
  {
    name: "Ja",
    moves: "x R2 F R F' R U2 r' U r U2",
    description: "Adjacent Corner Swap",
    category: "OLL",
  },
  {
    name: "Jb",
    moves: "R U R' F' R U R' U' R' F R2 U' R'",
    description: "Adjacent Corner Swap",
    category: "OLL",
  },
  {
    name: "Na",
    moves: "R U R' U R U R' F' R U R' U' R' F R2 U' R' U2 R U' R'",
    description: "Diagonal Corner Swap",
    category: "OLL",
  },
  {
    name: "Nb",
    moves: "R' U R U' R' F' U' F R U R' F R' F' R U' R",
    description: "Diagonal Corner Swap",
    category: "OLL",
  },
  {
    name: "Ra",
    moves: "R U' R' U' R U R D R' U' R D' R' U2 R'",
    description: "Adjacent Corner Swap",
    category: "OLL",
  },
  {
    name: "Rb",
    moves: "R2 F R U R U' R' F' R U2 R' U2 R",
    description: "Adjacent Corner Swap",
    category: "OLL",
  },
  {
    name: "T",
    moves: "R U R' U' R' F R2 U' R' U' R U R' F'",
    description: "Adjacent Corner Swap",
    category: "OLL",
  },
  {
    name: "Ua",
    moves: "M2 U M U2 M' U M2",
    description: "Edges Only",
    category: "OLL",
  },
  {
    name: "Ub",
    moves: "M2 U' M U2 M' U' M2",
    description: "Edges Only",
    category: "OLL",
  },
  {
    name: "V",
    moves: "R' U R' U' y R' F' R2 U' R' U R' F R F",
    description: "Diagonal Corner Swap",
    category: "OLL",
  },
  {
    name: "Y",
    moves: "F R U' R' U' R U R' F' R U R' U' R' F R F'",
    description: "Diagonal Corner Swap",
    category: "OLL",
  },
  {
    name: "Z",
    moves: "M' U M2 U M2 U M' U2 M2",
    description: "Edges Only",
    category: "OLL",
  },
] as const;
